version: '2.1'

services:
  slr_connector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slr_connector
    restart: always
    ports:
      - "30000:30000"
    volumes:
      - logs:/slr-connector/logs
    extra_hosts:
      - "rocky:10.0.0.7"
    mem_limit: 16g

volumes:
  logs: