version: '2.1'

services:
  slr_admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slr_admin
    restart: always
    ports:
      - "30010:30010"
    volumes:
      - logs:/slr-admin/logs
      - data:/slr-admin/data
    extra_hosts:
      - "rocky:10.0.0.7"
    mem_limit: 10g

volumes:
  data:
  logs: